#!/usr/bin/env bash
# Provision staging.elhabak.com on the production VPS — run as root. Idempotent: every
# step checks what already exists and never touches production (/var/www/elhabak, the
# `elhabak` database/role, the elhabak.com nginx site or its PM2 processes).
#
# Usage: bootstrap-staging.sh [--seed]
#   --seed   load the demo dataset into elhabak_staging (after the first staging deploy)
#
# Creates:
#   /var/www/elhabak-staging/{releases,shared/{storage,logs,backups}}
#   PostgreSQL role + database `elhabak_staging` (loopback only)
#   /var/www/elhabak-staging/shared/.env           (generated secrets, mode 600)
#   /var/www/elhabak-staging/shared/ecosystem.config.cjs  (api :4100, web :3100)
#   /etc/nginx/sites-available/elhabak-staging     (HTTPS, basic auth, noindex)
#   Let's Encrypt certificate for staging.elhabak.com (webroot)
#   /root/elhabak-staging-credentials.txt          (mode 600 — basic auth + demo logins)
#
# Secrets are generated here and written only to root-only files; nothing is printed.
set -euo pipefail

DOMAIN="staging.elhabak.com"
BASE="/var/www/elhabak-staging"
SHARED="$BASE/shared"
DB="elhabak_staging"
APP_USER="elhabak"
API_PORT=4100
WEB_PORT=3100
CRED="/root/elhabak-staging-credentials.txt"
PROD_ENV="/var/www/elhabak/shared/.env"
SITE="/etc/nginx/sites-available/elhabak-staging"
HTPASSWD="/etc/nginx/elhabak-staging.htpasswd"
OBSERVABILITY="/etc/nginx/conf.d/elhabak-observability.conf"

rand() { openssl rand -base64 64 | tr -dc 'A-Za-z0-9' | head -c "$1"; }
step() { echo ">> $1"; }

if [ "${1:-}" = "--seed" ]; then
  [ -d "$BASE/current" ] || { echo "FAIL: deploy staging first (ELHABAK_TARGET=staging deploy-release.sh)"; exit 1; }
  step "seeding demo dataset into $DB"
  cd "$BASE/current"
  pnpm db:seed
  chown -R "$APP_USER:$APP_USER" "$SHARED/storage"
  echo "SEED PASS"
  exit 0
fi

step "directories"
mkdir -p "$BASE/releases" "$SHARED/storage" "$SHARED/logs" "$SHARED/backups" /var/www/certbot
chown -R "$APP_USER:$APP_USER" "$BASE"

step "credentials file"
if [ ! -f "$CRED" ]; then
  (
    umask 077
    {
      echo "# staging.elhabak.com — generated by bootstrap-staging.sh. Root-only."
      echo "DB_PASSWORD=$(rand 32)"
      echo "BASIC_AUTH_USER=elhabak"
      echo "BASIC_AUTH_PASSWORD=$(rand 20)"
      for role in ADMIN ENGINEER ACCOUNTANT WORKER CLIENT; do
        echo "DEMO_${role}_PASSWORD=$(rand 16)"
      done
    } > "$CRED"
  )
fi
chmod 600 "$CRED"
# shellcheck disable=SC1090
. "$CRED"

step "database role + database ($DB, loopback)"
if ! su - postgres -c "psql -tAc \"select 1 from pg_roles where rolname='$DB'\"" | grep -q 1; then
  su - postgres -c psql >/dev/null <<SQL
CREATE ROLE $DB LOGIN PASSWORD '$DB_PASSWORD';
SQL
fi
if ! su - postgres -c "psql -tAc \"select 1 from pg_database where datname='$DB'\"" | grep -q 1; then
  su - postgres -c "createdb -O $DB $DB"
fi

step "shared env"
if [ ! -f "$SHARED/.env" ]; then
  prod_val() { grep -E "^$1=" "$PROD_ENV" 2>/dev/null | head -1 | cut -d= -f2-; }
  DB_URL="postgresql://$DB:$DB_PASSWORD@127.0.0.1:5432/$DB?schema=public"
  (
    umask 077
    cat > "$SHARED/.env" <<ENV
NODE_ENV=production
DATABASE_URL=$DB_URL
DIRECT_DATABASE_URL=$DB_URL
WEB_ORIGIN=https://$DOMAIN
EXTRA_WEB_ORIGINS=
API_PORT=$API_PORT
STORAGE_ROOT=$SHARED/storage
NEXT_PUBLIC_SITE_URL=https://$DOMAIN
NEXT_PUBLIC_API_BASE_URL=https://$DOMAIN/api
NEXT_PUBLIC_SOCKET_URL=https://$DOMAIN
AUTH_SESSION_SECRET=$(rand 64)
SESSION_COOKIE_NAME=elhabak_staging_session
SESSION_EXPIRES_DAYS=$(prod_val SESSION_EXPIRES_DAYS)
PUPPETEER_EXECUTABLE_PATH=$(prod_val PUPPETEER_EXECUTABLE_PATH)
DEMO_ADMIN_PASSWORD=$DEMO_ADMIN_PASSWORD
DEMO_ENGINEER_PASSWORD=$DEMO_ENGINEER_PASSWORD
DEMO_ACCOUNTANT_PASSWORD=$DEMO_ACCOUNTANT_PASSWORD
DEMO_WORKER_PASSWORD=$DEMO_WORKER_PASSWORD
DEMO_CLIENT_PASSWORD=$DEMO_CLIENT_PASSWORD
ENV
  )
fi
chmod 600 "$SHARED/.env"
chown "$APP_USER:$APP_USER" "$SHARED/.env"

step "pm2 ecosystem (api :$API_PORT, web :$WEB_PORT)"
cat > "$SHARED/ecosystem.config.cjs" <<ECO
module.exports = {
  apps: [
    {
      name: "elhabak-staging-api",
      cwd: "$BASE/current",
      script: "apps/api/dist/main.js",
      interpreter: "node",
      env: { NODE_ENV: "production" },
      autorestart: true,
      max_restarts: 10,
      restart_delay: 2000,
      max_memory_restart: "500M",
      kill_timeout: 8000,
      out_file: "$SHARED/logs/api-out.log",
      error_file: "$SHARED/logs/api-error.log",
      merge_logs: true,
      time: true
    },
    {
      name: "elhabak-staging-web",
      cwd: "$BASE/current/apps/web",
      script: "node_modules/next/dist/bin/next",
      args: "start -H 127.0.0.1 -p $WEB_PORT",
      interpreter: "node",
      env: { NODE_ENV: "production", PORT: "$WEB_PORT" },
      autorestart: true,
      max_restarts: 10,
      restart_delay: 2000,
      max_memory_restart: "500M",
      kill_timeout: 8000,
      out_file: "$SHARED/logs/web-out.log",
      error_file: "$SHARED/logs/web-error.log",
      merge_logs: true,
      time: true
    }
  ]
};
ECO
chown "$APP_USER:$APP_USER" "$SHARED/ecosystem.config.cjs"

step "basic auth"
if [ ! -f "$HTPASSWD" ]; then
  printf '%s:%s\n' "$BASIC_AUTH_USER" "$(openssl passwd -apr1 "$BASIC_AUTH_PASSWORD")" > "$HTPASSWD"
fi
chown root:www-data "$HTPASSWD"
chmod 640 "$HTPASSWD"

write_observability() {
  cat > "$OBSERVABILITY" <<'NGINX'
# ELHABAK request timing log format. Reused by production and staging sites.
log_format elhabak_timed '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" "$http_user_agent" '
                          'rt=$request_time uct=$upstream_connect_time '
                          'uht=$upstream_header_time urt=$upstream_response_time '
                          'upstream="$upstream_addr" gzip="$gzip_ratio"';
NGINX
}

write_http_only() {
  write_observability
  cat > "$SITE" <<'NGINX'
# ELHABAK staging — ACME bootstrap (replaced by the HTTPS site once the certificate exists)
server {
    listen 80;
    listen [::]:80;
    server_name staging.elhabak.com;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 404; }
}
NGINX
}

write_https() {
  write_observability
  cat > "$SITE" <<'NGINX'
# ELHABAK staging — staging.elhabak.com
# Web 127.0.0.1:3100, API 127.0.0.1:4100. Password-protected and never indexed.
# Reuses $elhabak_connection_upgrade from the production site (same http context).

server {
    listen 80;
    listen [::]:80;
    server_name staging.elhabak.com;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 301 https://staging.elhabak.com$request_uri; }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl;
    server_name staging.elhabak.com;

    ssl_certificate     /etc/letsencrypt/live/staging.elhabak.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/staging.elhabak.com/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;

    server_tokens off;
    access_log /var/log/nginx/elhabak-staging.access.log elhabak_timed;
    client_max_body_size 30m;
    client_body_timeout 60s;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript image/svg+xml;
    gzip_min_length 1024;

    add_header X-Robots-Tag "noindex, nofollow, noarchive" always;

    auth_basic "ELHABAK staging";
    auth_basic_user_file /etc/nginx/elhabak-staging.htpasswd;

    # Deploy health probe and install metadata stay reachable without the password.
    location = /api/health {
        auth_basic off;
        proxy_pass http://127.0.0.1:4100/health;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Browsers fetch the web app manifest (and its icons) without credentials.
    location ~ ^/(manifest\.webmanifest|apple-icon\.png|brand/icon-(192|512)\.png)$ {
        auth_basic off;
        proxy_pass http://127.0.0.1:3100;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /robots.txt {
        auth_basic off;
        default_type text/plain;
        return 200 "User-agent: *\nDisallow: /\n";
    }

    location /api/ {
        proxy_pass http://127.0.0.1:4100/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }

    location /socket.io/ {
        proxy_pass http://127.0.0.1:4100;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $elhabak_connection_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_buffering off;
    }

    location / {
        proxy_pass http://127.0.0.1:3100;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $elhabak_connection_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }
}
NGINX
}

reload_nginx() {
  nginx -t 2>&1 | tail -1
  nginx -t >/dev/null 2>&1 || { echo "FAIL: nginx config test failed — production config untouched, staging site disabled"; rm -f /etc/nginx/sites-enabled/elhabak-staging; nginx -t >/dev/null 2>&1 && systemctl reload nginx; exit 1; }
  systemctl reload nginx
}

step "nginx + certificate"
if [ ! -f "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" ]; then
  write_http_only
  ln -sfn "$SITE" /etc/nginx/sites-enabled/elhabak-staging
  reload_nginx
  certbot certonly --webroot -w /var/www/certbot -d "$DOMAIN" --non-interactive --agree-tos --keep-until-expiring >/dev/null
fi
write_https
ln -sfn "$SITE" /etc/nginx/sites-enabled/elhabak-staging
reload_nginx

echo "BOOTSTRAP PASS: $DOMAIN (credentials: $CRED)"
